name: PROD - Build and Deploy to GCP

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  ZONE: asia-northeast3
  IMAGE: prod
  SERVICE_ID: ${{ secrets.GCP_PROD_SERVICE_ID }}
  ARTIFACT_REGISTRY_REPO_NAME: tracer-ammunition-sveltekit

jobs:
  test:
    name: PROD - Test AND Docs Deploy Before Deploy to GCP
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
         node-version: ${{matrix.node_version}}
      - name: [Step 1] Install node_modules
        run: npm i
      - name: [Step 2] Build
        run: npm run build --if-present
      - name: [Step 3] Run Lint
        run: npm run lint
      - name: [Step 4] Run Unit Test
        run: npm test
      - name: [Step 5] Deploy Better-docs
        run: npm run doc
  deploy-to-artifact:
    needs: test
    name: PROD - Deploy to GCP
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: PROD - Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - run: |-
          gcloud --quiet auth configure-docker asia-northeast3-docker.pkg.dev

      # Build and Deploy Docker Image
      - name: PROD - Build
        run: |-
          gcloud builds submit \
            --tag "asia-northeast3-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_REPO_NAME/$IMAGE" --timeout "2h15m5s"
      - name: PROD - Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE_ID }}
          region: ${{ env.ZONE }}
          image: asia-northeast3-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO_NAME }}/${{ env.IMAGE }}:latest
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT }}