name: Test Before Merging

on:
  pull_request:
    branches: [main]

jobs:
  runs-on: ubuntu-latest
  strategy:
    build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.x]

      steps:
        - uses: actions/checkout@v1
        - name: Use Node.js ${{matrix.node-version}}
          uses: actions/setup-node@v1
          with:
            node-version: ${{matrix.node-version}}
        - name: npm install, build, and test
        - run: npm install
        - run: npm run lint
        - run: npm run test


